
services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8083:8080
    env_file:
      - .env
  nginx:
      image: nginx:latest
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - "80:80"
      depends_on:
        - server